apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-nginx

# deployment specification
spec:
  selector:
    matchLabels:
      app: hello-nginx
  replicas: 3 
  template:
    # info about the template
    metadata:
      labels:
        app: hello-nginx
    # Pod specification
    spec:
      containers:
        - name: nginx
          image: nginx:1.19.1-alpine
          ports:
            - containerPort: 80
          # setting resources limit 
          resources:
              requests:
                memory: "300Mi"
                cpu: "150m"
              limits:
                memory: "2Gi"
                cpu: "350m"                
          # volumes that will be mount
          volumeMounts:
            - mountPath: "/etc/nginx/conf.d"
              readOnly: true
              name: nginx-conf

      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
            items:
              - key: nginx.conf
                path: nginx.conf
